설명서 작성용 테스트
samchi31/Project202211 pull request #7
Opened 2022-11-09 11:26 UTC by facio313

2022-11-09 11:33 UTC, facio313 commented
이거는 반려해보세용

2022-11-09 14:31 UTC, samchi31 commented
이거 이후에 작성된 commit을 merge 해서 
conflict 발생함 충돌은 해결함

2022-11-09 14:36 UTC, samchi31 requested changes
conflict는 수정했으나 
이거 이후의 PL을 merge 해서  우찌해야될지...

2022-11-14 04:35 UTC, YOUNARAE approved these changes

2022-11-18 12:57 UTC, facio313 reviewed
ok

2022-11-18 12:57 UTC, closed without merging